
project_id = "wyqncdsniwajivzyktlr"

[functions.chat]
verify_jwt = false

[functions.update-secret-keys]
verify_jwt = true

[functions.get-secret-keys]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.ghl-client]
verify_jwt = true
